### ISSUE TITLE
Scope Document: Document API endpoints

### ISSUE THREAD

**Issue by avcopan** [avcopan/painless-panes#6]

**Comment by jma503** [comment]
https://docs.google.com/document/d/1X0RacYPR7wzYp3BW9FceCzJYZydmAURyEO4axuC8fs4/edit

Still making edits.

**Comment by avcopan** [comment]
Looks good, Josh! Some comments:
- The authentication routes are already written, so you can work off of my documentation [here](https://github.com/avcopan/painless-panes/blob/99c00a3c2dab3b02453e2016dd7ef67e7cb3e568/server/routes/email.router.cjs#L17). The three routes are:
    - POST /api/email/send   { "email": <> }
    - GET /api/email/verify?token=<>
    - GET /api/user
- POST for zip looks good, but I would go ahead and add in the route, such as /api/zip
- The other routes I think can be broken up based on what needs to be POSTed each time we hit the "Next" button in the form:
     - POST /api/frames/current should enter the current frames ID into the `project` table
     - POST /api/frames/desired should enter the desired frames ID into the `project` table
     - POST /api/locations should enter the list of window location IDs into the `project_locations` table
     - POST /api/window will enter all of the information (image, height, width, location_id) for a specific window into the `window` table

**Comment by avcopan** [comment]
Oh, and I forgot: we will also want to have a GET route for /api/locations that gets the list of window location IDs that the user entered. This can be used to populate a menu for the individual window pages for the user to identify the location of that window.
