### ISSUE TITLE
Confirmation Page: Allow user to click windows on confirmation page to edit them

### ISSUE THREAD

**Issue by steveshumaker** [avcopan/painless-panes#83]
Or, at least one page that aggregates all windows for a project with buttons to accept or edit the current window, add a window, and finalize project

**Comment by avcopan** [comment]
Is this an additional page, or a re-design / filling-in of Halima's confirmation page?

It might be helpful if you could sketch out some quick wireframes in excalidraw and post a quick description of what you're proposing in slack.

**Comment by steveshumaker** [comment]
Your comment made me re-think what I was thinking - the user shouldn't need to confirm a specific window, since they're able to edit and save dimensions/retake pictures/reselect frames. So I think Halima's current page works - as long as we can implement an edit functionality and select the window ID to edit somehow (can dig into this or someone else can take it) I think we're good to go. Let me know what you think!

Edit - tied to the TODO in the backlog that basically captures what I was thinking

**Comment by avcopan** [comment]
Agreed!
