### ISSUE TITLE
Adding Images Page: Allow user to add multiple windows to their submission [DONE]. Addition - add a little more functionality/user friendliness

### ISSUE THREAD

**Issue by Brandon-Paulson** [avcopan/painless-panes#88]

**Comment by steveshumaker** [comment]
Added myself to this as well - working base functionality (Brandon). 

- Button to add an image conditionally renders if the user has finalized a frame 
- Logic to clear inputs handled in useEffect of addImage and addImageFormViews or whatever component
- Button moved to where it would be logically; below the frame selection but before the 'next' button

**TODO**

- Display an alert of some sort when an image is finalized by the user (frame selected and select 'save'?) As it is right now, it should be just after frame selection.
- Turn the add image into something that is styled better than it currently is
